import { Persona, Facility } from "@/types";

export const personas: Persona[] = [
  {
    id: "alex",
    name: "Alex (Student)",
    avatar: "🎓",
    description: "UMD grad student, tight budget",
    insurance_type: "HDHP",
    deductible_remaining: 1200,
    urgent_care_copay: 75,
    er_copay: 350,
    coinsurance_percentage: 20,
    location: "College Park, MD",
    simulated_time: "14:30",
    simulated_day: "Monday",
    bank_balance: 420,
  },
  {
    id: "jordan",
    name: "Jordan (Staff)",
    avatar: "💼",
    description: "UMD staff, good PPO coverage",
    insurance_type: "PPO",
    deductible_remaining: 0,
    urgent_care_copay: 30,
    er_copay: 150,
    coinsurance_percentage: 10,
    location: "College Park, MD",
    simulated_time: "22:15",
    simulated_day: "Saturday",
    bank_balance: 3200,
  },
];

export const facilities: Facility[] = [
  {
    id: "f1",
    type: "Urgent Care",
    name: "GoHealth Urgent Care",
    network_status: "In-Network",
    hours_open: "08:00",
    hours_close: "20:00",
    days_open: ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],
    capabilities: ["X-ray","Labs","Minor injuries","Infections","Flu/COVID testing"],
    wait_time_minutes: 25,
    address: "7310 Baltimore Ave, College Park MD",
  },
  {
    id: "f2",
    type: "Emergency Room",
    name: "University of Maryland Medical Center ER",
    network_status: "In-Network",
    hours_open: "00:00",
    hours_close: "23:59",
    days_open: ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],
    capabilities: ["Full emergency care","Surgery","Cardiac","Stroke","Trauma","CT/MRI"],
    wait_time_minutes: 180,
    address: "22 S Greene St, Baltimore MD",
  },
  {
    id: "f3",
    type: "Telehealth",
    name: "UMD Health Portal — Virtual Visit",
    network_status: "In-Network",
    hours_open: "00:00",
    hours_close: "23:59",
    days_open: ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],
    capabilities: ["Prescriptions","Mental health","Cold/flu","Skin conditions","Follow-ups"],
    wait_time_minutes: 8,
    address: "Virtual — health.umd.edu/telehealth",
  },
];
